---
controller_credentials:
- name: HAProxy Statistics - profile_haproxy
  description: Credential for profile_haproxy
  organization: Default
  credential_type: HAProxy Statistics
  update_secrets: true
  inputs:
    stats_user: '{{ stats_user }}'
    stats_password: '{{ vault_stats_password }}'
- name: HAProxy SSL Certificate - profile_haproxy
  description: Credential for profile_haproxy
  organization: Default
  credential_type: HAProxy SSL Certificate
  update_secrets: true
  inputs:
    ssl_cert_path: '{{ ssl_cert_path }}'
    ssl_key_path: '{{ ssl_key_path }}'
